In [36]:
import pandas as pd
from datetime import datetime

In [37]:
df_degradations = pd.read_csv(r'D:\Top_gun\Data_clean\Update_degradations_2024-06-12.csv')
df_logs_vols = pd.read_csv(r'D:\Top_gun\Data_clean\Update_logs_vols_2024-06-12.csv')

In [38]:
# mettre au format datetime
df_degradations['measure_day'] = pd.to_datetime(df_degradations['measure_day'])
df_degradations.head()

,ref_deg,linked_aero,compo_concerned,usure_nouvelle,measure_day,need_replacement
0,D003661,E170_6353,REAE170-E170_6353-0,53.0,2024-06-01,0
1,D009402,E170_6353,REAE170-E170_6353-1,50.0,2024-06-01,0
2,D000812,E170_6353,SYSE170-E170_6353-2,17.0,2024-06-01,0
3,D006665,E170_6353,ORDE170-E170_6353-3,7.0,2024-06-01,0
4,D001163,E170_6353,AUTE170-E170_6353-4,42.0,2024-06-01,0

In [39]:
df_degradations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1168830 entries, 0 to 1168829
Data columns (total 6 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   ref_deg           1168830 non-null  object
 1   linked_aero       1168830 non-null  object
 2   compo_concerned   1168830 non-null  object
 3   usure_nouvelle    1168830 non-null  float64
 4   measure_day       1146645 non-null  datetime64[ns]
 5   need_replacement  1168830 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 53.5+ MB

In [40]:
# mettre au format datetime
df_logs_vols['jour_vol'] = pd.to_datetime(df_logs_vols['jour_vol'])
df_logs_vols.head()

,ref_vol,aero_linked,jour_vol,time_en_air,etat_voyant,temp en °C,pressure en hPa,vibrations en m/s²
0,V07679725,B767_4924,2024-06-02,7.0,0,-5.7,930.6,3.116
1,V02564879,B747_3165,2024-06-02,5.1,0,0.9,950.6,4.558
2,V07933973,B757_2518,2024-06-02,7.7,3,-6.2,975.5,4.587
3,V02230187,A340_1047,2024-06-02,6.1,1,-25.3,945.1,3.288
4,V09071213,B757_6806,2024-06-02,4.5,0,11.1,931.3,2.817

In [41]:
df_logs_vols.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1238 entries, 0 to 1237
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ref_vol             1238 non-null   object
 1   aero_linked         1238 non-null   object
 2   jour_vol            1238 non-null   datetime64[ns]
 3   time_en_air         1238 non-null   float64
 4   etat_voyant         1238 non-null   int64
 5   temp en °C          1238 non-null   float64
 6   pressure en hPa     1238 non-null   float64
 7   vibrations en m/s²  1238 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(2)
memory usage: 77.5+ KB

In [42]:
# Exporter les données en écrasant les fichiers existants a la date du jour
today_str = datetime.today().strftime('%Y-%m-%d')
df_logs_vols.to_csv(r'D:\Top_gun\Data_clean\df_logs_vols_'+today_str+'.csv', index=False)
df_degradations.to_csv(r'D:\Top_gun\Data_clean\df_degradations_'+today_str+'.csv', index=False)